name: opentelemetry-collector-action
description: Action to docker run opentelemetry-collector

inputs:
  image:
    description: Container image URI
    required: true
    default: otel/opentelemetry-collector-contrib:0.109.0
  config:
    description: Inline config
    required: false
  config-path:
    description: Path to the configuration file
    required: false
  environments:
    description: Environment variables propataged to the container
    required: false
  ports:
    description: Ports to expose
    required: false
    default: |
      4317:4317
      4318:4318

outputs:
  container-id:
    description: Container ID

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
